# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9b9c51ae-3007-4f8a-9837-a01bb4309d1c";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9b9c51ae-3007-4f8a-9837-a01bb4309d1c";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9b9c51ae-3007-4f8a-9837-a01bb4309d1c";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/9b9c51ae-3007-4f8a-9837-a01bb4309d1c";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/9b9c51ae-3007-4f8a-9837-a01bb4309d1c";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/9b9c51ae-3007-4f8a-9837-a01bb4309d1c";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  # 0077, not the generated default 0022: vfat has no ownership of its own, so
  # the mask is the only access control the ESP gets. systemd-boot-random-seed
  # refuses to treat /boot/loader/random-seed as secret while the mount is
  # world-readable and logs it as "a security hole" on every boot. Only root
  # reads the ESP from Linux, and the firmware ignores unix permissions
  # entirely, so tightening this costs nothing.
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CED8-DF10";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Big 5.5T btrfs data disk (RAID0 over sda+sdb). Holds Immich media
  # (/data/immich), the local Borg repo (/data/borg), and existing movies/tv.
  # subvol=/ is the top-level subvolume (subvolid 5) where that content lives.
  # nofail so a missing/degraded disk never blocks boot.
  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/75c4fbbf-7ab0-42f2-b333-31d825d280c2";
      fsType = "btrfs";
      options = [ "subvol=/" "compress=zstd" "noatime" "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
