# Hardware configuration for sulfur
# Generated by install.sh with impermanence support
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # rtsx_pci_sdmmc deliberately NOT here. install.sh's generated list scooped up every
  # storage driver present on the installer, but root is LUKS-on-NVMe, so the Realtek
  # RTS525A card reader is not on the boot path and the initrd has no reason to probe
  # it. Keep it out on those grounds alone.
  #
  # It did NOT fix the 26.11 boot hang, and the reason is worth recording: the fault is
  # at the PCIe link layer, below any driver. Removing the module changes nothing about
  # whether the link retries. See pcie_aspm=off in boot.kernelParams for the actual fix.
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];

  # Kernel parameters
  boot.kernelParams = [
    "nvme_core.default_ps_max_latency_us=0"
    "i915.enable_psr=0"  # Disable PSR to fix aux errors on Arrow Lake graphics

    # Brightness keys/slider did nothing: intel_backlight exists but writes to it
    # never moved the panel. The kernel told us why during eDP-1 probe:
    #   [drm] [CONNECTOR:262:eDP-1] Panel is missing HDR static metadata. Possible
    #   support for Intel HDR backlight interface is not used. If your backlight
    #   controls don't work try booting with i915.enable_dpcd_backlight=3.
    # nixos-hardware's asus module sets =1 (DPCD, non-HDR); this panel needs =3
    # (DPCD incl. the HDR/VESA interface). Our params are appended after the
    # module's, and last-wins for an int modparam, so =3 overrides =1. Verify:
    #   cat /proc/cmdline   # -> ...enable_dpcd_backlight=3 must appear LAST
    "i915.enable_dpcd_backlight=3"

    # NOTE (dead-but-harmless): the NVreg line below was an attempt to suppress the
    # phantom nvidia_0 raw backlight so mutter couldn't bind to it. It does NOT work
    # on the OPEN nvidia driver - the correct token applies (params show
    # EnableBrightnessControl=0) yet nvidia_0 still spawns. Kept only because losing
    # it changes nothing; the real backlight fix is enable_dpcd_backlight=3 above.
    # If mutter is ever seen driving nvidia_0 after resume, mask it via udev instead.
    "nvidia.NVreg_RegistryDwords=EnableBrightnessControl=0"

    # WHY 26.11 WOULD NOT BOOT (2026-08-11). Linux 6.18.44 turned this laptop's
    # long-standing PCIe grumble into a livelock. The Realtek RTS525A card reader at
    # 0000:2c:00.0 (device 10ec:525a, under root port 00:1c.0) storms correctable AER
    # errors -- status=0x00001000, bit 12, Replay Timer Timeout -- roughly every 150
    # MICROSECONDS. Four log lines per event, thousands of events per second, and the
    # kernel spends the whole boot in the AER handler instead of finishing it.
    #
    # Replay Timer Timeout means the link ran out of time waiting to be acked and
    # retried. On this Realtek reader that is the textbook symptom of ASPM L1 substates
    # letting the link doze off too aggressively; 6.18.43 kept the same link quiet
    # enough to produce exactly ten of these per boot, 6.18.44 does not.
    #
    # pcie_aspm=off disables PCIe Active State Power Management link-wide. Costs some
    # idle battery -- that is the trade for a machine that boots. If this proves to be
    # the fix, the follow-up is to narrow it (pcie_aspm.policy=performance, or disable
    # the reader outright via udev since the SD slot is expendable) rather than leave
    # ASPM off across the board.
    #
    # NOTE: the errors are Correctable. The hardware is recovering every one of them --
    # nothing is silently corrupting. The failure is the cost of REPORTING them.
    "pcie_aspm=off"
  ];

  # LUKS configuration
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/67cacaa1-f13e-4984-a84b-905d09d416aa";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  # Ephemeral root on tmpfs
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=6G" "mode=755" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@persist" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@swap" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/08E2-FB95";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Swap file on Btrfs (32GB for hibernation support)
  swapDevices = [{
    device = "/swap/swapfile";
    size = 32768;
  }];

  # Optimize I/O scheduler for NVMe
  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
  '';

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
