# sulfur's disks and hardware quirks. Generated by install.sh, then hand-tuned.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # rtsx_pci_sdmmc deliberately absent: root is LUKS-on-NVMe, so the card reader is not on
  # the boot path. It did not fix the 26.11 boot hang either -- that fault is at the PCIe
  # link layer, below any driver. See pcie_aspm=off below.
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];

  boot.kernelParams = [
    "nvme_core.default_ps_max_latency_us=0"
    "i915.enable_psr=0"  # Disable PSR to fix aux errors on Arrow Lake graphics

    # This panel needs the DPCD interface including HDR/VESA; nixos-hardware's asus module
    # sets =1, and ours are appended after, so last-wins for an int modparam. Verify with
    # `cat /proc/cmdline` -- =3 must appear LAST.
    "i915.enable_dpcd_backlight=3"


    # The Realtek card reader storms correctable AER errors (Replay Timer Timeout) every
    # ~150 us and the kernel spends the whole boot in the AER handler. The errors are
    # correctable -- nothing corrupts; the failure is the cost of REPORTING them. Costs idle
    # battery, and narrowing it is an open item. See CHANGELOG 2026-08-11.
    "pcie_aspm=off"
  ];

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/67cacaa1-f13e-4984-a84b-905d09d416aa";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  # Ephemeral root.
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=6G" "mode=755" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@persist" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@swap" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/08E2-FB95";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # 32 GB, sized for hibernation.
  swapDevices = [{
    device = "/swap/swapfile";
    size = 32768;
  }];

  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
  '';

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
