# Hardware configuration for sulphur
# Generated by install.sh with impermanence support
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];

  # Kernel parameters
  boot.kernelParams = [
    "nvme_core.default_ps_max_latency_us=0"
    "i915.enable_psr=0"  # Disable PSR to fix aux errors on Arrow Lake graphics
    # Suppress the phantom nvidia_0 backlight so GNOME/mutter can only pick the
    # real eDP panel (intel_backlight). In Hybrid mode nvidia_0 is a stuck, unwired
    # raw backlight; on resume the eDP connector briefly re-probes and mutter falls
    # back to the "first raw" device - nvidia_0 (PCI 01:00.0 sorts before Intel's
    # 00:02.0) - then caches it, so keys/slider silently drive a dead device.
    #
    # nixos-hardware's asus/zephyrus/shared/backlight.nix tries to do this but has
    # a typo: "NVReg_RegistryDwords" (capital R) is not a valid nvidia token and is
    # silently ignored (/proc/driver/nvidia/params shows RegistryDwords empty). The
    # correct token is "NVreg_"; this line overrides it. Verify after boot:
    #   grep RegistryDwords /proc/driver/nvidia/params   # -> EnableBrightnessControl=0
    #   ls /sys/class/backlight/                         # -> intel_backlight only
    "nvidia.NVreg_RegistryDwords=EnableBrightnessControl=0"
  ];

  # LUKS configuration
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/67cacaa1-f13e-4984-a84b-905d09d416aa";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  # Ephemeral root on tmpfs
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=6G" "mode=755" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@persist" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@swap" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/08E2-FB95";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Swap file on Btrfs (32GB for hibernation support)
  swapDevices = [{
    device = "/swap/swapfile";
    size = 32768;
  }];

  # Optimize I/O scheduler for NVMe
  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
  '';

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
