# Hardware configuration for sulphur
# Generated by install.sh with impermanence support
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "uas" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];

  # Kernel parameters
  boot.kernelParams = [
    "nvme_core.default_ps_max_latency_us=0"
    "i915.enable_psr=0"  # Disable PSR to fix aux errors on Arrow Lake graphics

    # Brightness keys/slider did nothing: intel_backlight exists but writes to it
    # never moved the panel. The kernel told us why during eDP-1 probe:
    #   [drm] [CONNECTOR:262:eDP-1] Panel is missing HDR static metadata. Possible
    #   support for Intel HDR backlight interface is not used. If your backlight
    #   controls don't work try booting with i915.enable_dpcd_backlight=3.
    # nixos-hardware's asus module sets =1 (DPCD, non-HDR); this panel needs =3
    # (DPCD incl. the HDR/VESA interface). Our params are appended after the
    # module's, and last-wins for an int modparam, so =3 overrides =1. Verify:
    #   cat /proc/cmdline   # -> ...enable_dpcd_backlight=3 must appear LAST
    "i915.enable_dpcd_backlight=3"

    # NOTE (dead-but-harmless): the NVreg line below was an attempt to suppress the
    # phantom nvidia_0 raw backlight so mutter couldn't bind to it. It does NOT work
    # on the OPEN nvidia driver - the correct token applies (params show
    # EnableBrightnessControl=0) yet nvidia_0 still spawns. Kept only because losing
    # it changes nothing; the real backlight fix is enable_dpcd_backlight=3 above.
    # If mutter is ever seen driving nvidia_0 after resume, mask it via udev instead.
    "nvidia.NVreg_RegistryDwords=EnableBrightnessControl=0"
  ];

  # LUKS configuration
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/67cacaa1-f13e-4984-a84b-905d09d416aa";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  # Ephemeral root on tmpfs
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=6G" "mode=755" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@persist" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd" "noatime" "discard=async" ];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [ "subvol=@swap" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/08E2-FB95";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Swap file on Btrfs (32GB for hibernation support)
  swapDevices = [{
    device = "/swap/swapfile";
    size = 32768;
  }];

  # Optimize I/O scheduler for NVMe
  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
  '';

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
