{ config, pkgs, lib, ... }: {
  imports = [
    ../hardware/hydrogen.nix          # generated by install.sh (disk UUIDs/mounts)
    ../modules/core.nix
    ../modules/sops.nix
    ../modules/impermanence-server.nix
    ../modules/reverse-proxy.nix
    ../modules/nextcloud.nix
    ../modules/immich.nix
    ../modules/calibre.nix
    ../modules/paperless.nix
    ../modules/scanner.nix
    ../modules/ollama.nix             # local LLM inference (loopback only), for paperless
    ../modules/backup.nix
    ../modules/auto-update.nix        # nightly stable-branch security updates (server runs 24/7)
    ../modules/fleet-vpn.nix          # on-demand WireGuard tunnel to the Jellyfin fleet (manual switch)
    ../modules/minecraft-server.nix   # persistent vanilla world (system service, no session needed)
    ../modules/minecraft-couch.nix    # 1-4 player split-screen launcher on the projector
    ../modules/minecraft-mods.nix     # declarative Fabric client mods, shared with sulfur
    # ../modules/veloren-server.nix   # DISABLED 2026-08-03 -- see below
    #
    # Veloren's rtsim (1867 NPCs across 196 sites) never idles: measured 20.7% of a core
    # continuously with ZERO players connected, versus 0.10% for the Minecraft server, which
    # does pause when empty (pause-when-empty-seconds, vanilla default 60). Nobody is playing
    # Veloren, so that is a permanent ~0.2 cores and ~700 MiB for nothing.
    #
    # To re-enable: uncomment the import above and the two ports in the br0 firewall lists
    # below. /var/lib/veloren is left in place, so characters and terrain diffs survive; even
    # if it were deleted the world regenerates identically from the pinned world_seed.
    # modules/veloren-server.nix and docs/veloren.md are unchanged.
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Adds a "Memory Test (memtest86+)" entry to the systemd-boot menu. Used to
  # diagnose the transient btrfs csum failures (RAM the prime suspect).
  boot.loader.systemd-boot.memtest86.enable = true;

  # Keep the couch Prism instance's mods folder pointed at the current jar set.
  # minecraft-couch-sync also does this, but the service covers the case where the
  # mod list changes and nobody re-syncs before the next couch session.
  services.minecraftClientMods.instances = [ "couch" ];

  networking.hostName = "hydrogen"; # Define your hostname.

  # Enable networking. Plain `false` (not mkDefault) to override the mkDefault true
  # written into the generated hardware/hydrogen.nix; the static br0 bridge is used.
  networking.useDHCP = false;
  networking.wireless.enable = false;
  networking.bridges = {
    "br0" = {
      interfaces = ["enp0s31f6"];
    };
  };
  networking.interfaces.br0.ipv4.addresses = [{
    address = "10.0.0.10";
    prefixLength = 24;
  }];
  #networking.interfaces.enp0s31f6.ipv4.addresses = [{
    #address = "10.0.0.10";
    #prefixLength = 24;
  #}];
  networking.defaultGateway = "10.0.0.1";
  networking.nameservers = [ "10.0.0.1" ];
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = [
    22
    80
    443
    6789
    7878
    8096
    8989
  ];
  environment.systemPackages = with pkgs; [
    rustdesk-flutter   # RustDesk host (this box is remote-controlled); LAN direct-IP
    rustup
    firefox
    git
    curl
    wget
    htop
    tree
    ripgrep
    srm
    vlc
    p7zip
    neovim
    tmux
    rsync
    go

    # Veloren client (veloren-voxygen). Same derivation as the server in
    # modules/veloren-server.nix, which is the point: Veloren refuses cross-version
    # connections, so client and server must come from one flake pin. Airshipper is
    # not a substitute — it self-updates to upstream's weekly nightlies.
    veloren
  ];

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable libvirt
  virtualisation.libvirtd.enable = true;

  # Enable the GNOME Desktop Environment.
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  # NOTE: autoLogin for sheath is already enabled further below — that running
  # session (on the laptop's eDP panel) is what RustDesk captures for remote clients.

  # GNOME's power daemon initiates idle-suspend on its own (independent of the
  # masked systemd sleep targets below). hydrogen is a 24/7 server — never let
  # the session auto-suspend on idle. Also disable the lock screen + idle blanking
  # so remote-desktop capture (RustDesk) always has a live desktop on the eDP panel.
  # Applies to fresh sessions after rebuild.
  services.desktopManager.gnome.extraGSettingsOverrides = ''
    [org.gnome.settings-daemon.plugins.power]
    sleep-inactive-ac-type='nothing'
    sleep-inactive-battery-type='nothing'

    [org.gnome.desktop.screensaver]
    lock-enabled=false
    idle-activation-enabled=false

    [org.gnome.desktop.session]
    idle-delay=uint32 0
  '';
  services.desktopManager.gnome.extraGSettingsOverridePackages = [ pkgs.gnome-settings-daemon ];

  # RustDesk direct-IP remote desktop (LAN). Captures via the xdg-desktop-portal
  # ScreenCast path, which works on this NVIDIA+Wayland box — unlike gnome-remote-desktop
  # RDP (blank frames, mutter #3297) and Sunshine KMS capture (GL_INVALID_VALUE), both
  # tried and abandoned. Host app runs in the autologin session; set an unattended
  # password + enable direct-IP in its Security settings. 21118 is the direct-access
  # port; open its full range.
  networking.firewall.interfaces."br0".allowedTCPPorts = [
    21115 21116 21117 21118 21119   # RustDesk (see above)

    # Minecraft (modules/minecraft-server.nix). Scoped to br0 rather than opened
    # globally: the server runs online-mode=false and performs no identity
    # verification, so reachability IS the authentication boundary.
    #
    # There is no wg0 on this host — the WireGuard hub lives on the router
    # (vpn.luckyobserver.com, tunnel 10.40.0.0/24) and remote peers route to
    # hydrogen's LAN address 10.0.0.10, so tunnel traffic ingresses on br0 just
    # like LAN traffic. This rule therefore admits the home LAN and enrolled
    # peers, and nothing else: the router forwards only 51820/udp, so 25565 is
    # not reachable from the internet. Verify that from off-tunnel after any
    # router change — it is the single most important check for this service.
    25565

    # Veloren game port (modules/veloren-server.nix). Closed alongside the disabled
    # import above; re-open with it. Scoped to br0 for exactly the reason spelled out
    # for 25565: the server runs with auth_server_address: None and verifies no
    # identity, so reachability IS the authentication boundary.
    # 14004
  ];
  networking.firewall.interfaces."br0".allowedUDPPorts = [
    21116   # RustDesk
    # 14006 # Veloren server-browser query — closed with the disabled import above
  ];

  # Auto-start the RustDesk host with the (autologin) graphical session, so the box
  # accepts connections after boot without launching it by hand. Runs as a user
  # service under graphical-session.target so it inherits the Wayland/DBus/portal
  # env needed for screen capture. Unattended password + direct-IP are set once in
  # the app (stateful, in ~/.config/rustdesk).
  systemd.user.services.rustdesk = {
    description = "RustDesk remote-desktop host";
    partOf = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    wantedBy = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.rustdesk-flutter}/bin/rustdesk";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enable automatic login for the primary user.
  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "sheath";

  # Workaround for GNOME autologin: https://github.com/NixOS/nixpkgs/issues/103746#issuecomment-945091229
  systemd.services."getty@tty1".enable = false;
  systemd.services."autovt@tty1".enable = false;

  # Disable suspend. The masks are the last line of defence and stay: an
  # unnoticed suspend would take Minecraft, Nextcloud, Immich, Paperless and the
  # nightly backups offline at once, which is far worse than a failed attempt.
  systemd.targets.sleep.enable = false;
  systemd.targets.suspend.enable = false;
  systemd.targets.hibernate.enable = false;
  systemd.targets.hybrid-sleep.enable = false;

  # ...but logind must never TRY, because a masked target is not a graceful "no".
  #
  # 2026-08-04: systemd-logind wedged in a tight retry loop -- "Suspending..." ->
  # "Unit suspend.target is masked, refusing operation." -> "Permission denied",
  # roughly 240 times a second, burning 75% of a core. A bus capture showed ZERO
  # messages addressed to login1: nothing asked it to suspend, it was re-querying
  # suspend.target's LoadState from PID 1 on its own and never clearing the
  # pending operation. It produced ~7M journal lines in four hours, which blew
  # past journald's retention and evicted the rest of the day -- including the
  # 03:00 backup window, so the nightly borg run had no diagnosable record.
  #
  # The masks are what turn a refusal into a livelock, so the fix is to make
  # logind never initiate a sleep operation in the first place. SleepOperation=
  # (empty) leaves it no candidate operation at all; the Handle*Key entries stop
  # a stray ACPI/keyboard event from starting one. IdleAction and the lid
  # switches were already covered.
  #
  # If this ever recurs, it is one command to confirm:
  #   journalctl -u systemd-logind | grep -c "refusing operation"
  # and `systemctl restart systemd-logind` clears the wedged state.
  services.logind.settings.Login = {
    IdleAction = "ignore";
    HandleLidSwitch = "ignore";
    HandleLidSwitchDocked = "ignore";
    HandleLidSwitchExternalPower = "ignore";
    HandleSuspendKey = "ignore";
    HandleSuspendKeyLongPress = "ignore";
    HandleHibernateKey = "ignore";
    HandleHibernateKeyLongPress = "ignore";
    SleepOperation = "";
  };

  # Xeon E-2176M with HWP. The default balanced energy-performance preference
  # leaves frames on the table under sustained load (four Minecraft clients plus
  # the server), and this box is mains-powered 24/7.
  powerManagement.cpuFreqGovernor = "performance";

  # (allowUnfree is set centrally in flake.nix commonModules)

  # Enable the OpenSSH daemon.
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
    settings.PermitRootLogin = "no";
  };

  # PostgreSQL for nextcloud + immich (shared instance). Pinned explicitly rather
  # than tracking the stateVersion default, so future stateVersion bumps don't
  # silently trigger another major upgrade. Moving 15 -> 17 is a deliberate
  # dump/restore migration (see docs/plan); the pg15 data dir is left intact.
  services.postgresql.package = pkgs.postgresql_17;

  # Enable NVIDIA
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.graphics.enable = true;
  # Cheap insurance against a Steam/Proton-shaped "missing 32-bit lib" rabbit
  # hole later; costs a few hundred MB of closure.
  hardware.graphics.enable32Bit = true;
  # Driver >= 560 requires an explicit choice of kernel module flavour.
  # Closed modules are the safe default for unknown/pre-Turing GPUs.
  hardware.nvidia.open = false;

  # The Quadro P4200 is Pascal (GP104GLM), and Pascal is end-of-life: R580 is the
  # last branch NVIDIA supports for Maxwell/Pascal/Volta, with critical security
  # updates for Quadro parts through October 2028 but no further feature updates.
  # Every branch in the current nixpkgs pin (stable/latest/beta/production) is
  # 580.142, so this pin is a no-op TODAY — its job is to stop the nightly
  # auto-update (modules/auto-update.nix) from silently moving the GPU onto a 590
  # branch that does not support this card. Revisit deliberately at the next
  # NixOS release bump; when nixpkgs grows a legacy_580 attribute, switch to it.
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.production;

  # nix-ld so generic dynamically-linked binaries run (e.g. the official Claude
  # Code CLI in ~/.local/bin). Mirrors sulfur's modules/workstation.nix config.
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      zstd
      stdenv.cc.cc.lib
      zlib
      glib
      libGL
      libx11
      libxcursor
      libxrandr
      libxi
      libxkbcommon
      wayland
      fontconfig
      freetype
      dbus
    ];
  };

  # Enable Syncthing
  services.syncthing.enable = true;
  # GUI stays on localhost (default 127.0.0.1:8384) — reach it via SSH port-forward:
  #   ssh -L 8384:localhost:8384 sheath@10.0.0.10  ->  http://localhost:8384
  # Only open the sync protocol ports (22000/tcp+udp, 21027/udp discovery).
  services.syncthing.openDefaultPorts = true;

  # Disk layout, initrd modules, swap, hostPlatform and microcode all come from the
  # installer-generated ../hardware/hydrogen.nix (single source of disk-dependent config).
  hardware.enableRedistributableFirmware = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # bumped 23.11 -> 25.11 alongside the pg15->17 migration
}
