{ config, pkgs, lib, ... }: {
  imports = [
    ../hardware/hydrogen.nix          # generated by install.sh (disk UUIDs/mounts)
    ../modules/core.nix
    ../modules/sops.nix
    ../modules/impermanence-server.nix
    ../modules/reverse-proxy.nix
    ../modules/nextcloud.nix
    ../modules/immich.nix
    ../modules/calibre.nix
    ../modules/paperless.nix
    ../modules/scanner.nix
    ../modules/backup.nix
    ../modules/auto-update.nix        # nightly stable-branch security updates (server runs 24/7)
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Adds a "Memory Test (memtest86+)" entry to the systemd-boot menu. Used to
  # diagnose the transient btrfs csum failures (RAM the prime suspect).
  boot.loader.systemd-boot.memtest86.enable = true;

  networking.hostName = "hydrogen"; # Define your hostname.

  # Enable networking. Plain `false` (not mkDefault) to override the mkDefault true
  # written into the generated hardware/hydrogen.nix; the static br0 bridge is used.
  networking.useDHCP = false;
  networking.wireless.enable = false;
  networking.bridges = {
    "br0" = {
      interfaces = ["enp0s31f6"];
    };
  };
  networking.interfaces.br0.ipv4.addresses = [{
    address = "10.0.0.10";
    prefixLength = 24;
  }];
  #networking.interfaces.enp0s31f6.ipv4.addresses = [{
    #address = "10.0.0.10";
    #prefixLength = 24;
  #}];
  networking.defaultGateway = "10.0.0.1";
  networking.nameservers = [ "10.0.0.1" ];
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = [
    22
    80
    443
    6789
    7878
    8096
    8989
  ];
  environment.systemPackages = with pkgs; [
    rustdesk-flutter   # RustDesk host (this box is remote-controlled); LAN direct-IP
    rustup
    firefox
    git
    curl
    wget
    htop
    tree
    ripgrep
    srm
    vlc
    p7zip
    neovim
    tmux
    rsync
    go
  ];

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable libvirt
  virtualisation.libvirtd.enable = true;

  # Enable the GNOME Desktop Environment.
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  # NOTE: autoLogin for sheath is already enabled further below — that running
  # session (on the laptop's eDP panel) is what RustDesk captures for remote clients.

  # GNOME's power daemon initiates idle-suspend on its own (independent of the
  # masked systemd sleep targets below). hydrogen is a 24/7 server — never let
  # the session auto-suspend on idle. Also disable the lock screen + idle blanking
  # so remote-desktop capture (RustDesk) always has a live desktop on the eDP panel.
  # Applies to fresh sessions after rebuild.
  services.desktopManager.gnome.extraGSettingsOverrides = ''
    [org.gnome.settings-daemon.plugins.power]
    sleep-inactive-ac-type='nothing'
    sleep-inactive-battery-type='nothing'

    [org.gnome.desktop.screensaver]
    lock-enabled=false
    idle-activation-enabled=false

    [org.gnome.desktop.session]
    idle-delay=uint32 0
  '';
  services.desktopManager.gnome.extraGSettingsOverridePackages = [ pkgs.gnome-settings-daemon ];

  # RustDesk direct-IP remote desktop (LAN). Captures via the xdg-desktop-portal
  # ScreenCast path, which works on this NVIDIA+Wayland box — unlike gnome-remote-desktop
  # RDP (blank frames, mutter #3297) and Sunshine KMS capture (GL_INVALID_VALUE), both
  # tried and abandoned. Host app runs in the autologin session; set an unattended
  # password + enable direct-IP in its Security settings. 21118 is the direct-access
  # port; open its full range.
  networking.firewall.interfaces."br0".allowedTCPPorts = [ 21115 21116 21117 21118 21119 ];
  networking.firewall.interfaces."br0".allowedUDPPorts = [ 21116 ];

  # Auto-start the RustDesk host with the (autologin) graphical session, so the box
  # accepts connections after boot without launching it by hand. Runs as a user
  # service under graphical-session.target so it inherits the Wayland/DBus/portal
  # env needed for screen capture. Unattended password + direct-IP are set once in
  # the app (stateful, in ~/.config/rustdesk).
  systemd.user.services.rustdesk = {
    description = "RustDesk remote-desktop host";
    partOf = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    wantedBy = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.rustdesk-flutter}/bin/rustdesk";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enable automatic login for the primary user.
  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "sheath";

  # Workaround for GNOME autologin: https://github.com/NixOS/nixpkgs/issues/103746#issuecomment-945091229
  systemd.services."getty@tty1".enable = false;
  systemd.services."autovt@tty1".enable = false;

  # Disable suspend
  systemd.targets.sleep.enable = false;
  systemd.targets.suspend.enable = false;
  systemd.targets.hibernate.enable = false;
  systemd.targets.hybrid-sleep.enable = false;
  # Don't let logind suspend/shut down on idle either (belt-and-suspenders).
  services.logind.settings.Login.IdleAction = "ignore";

  # (allowUnfree is set centrally in flake.nix commonModules)

  # Enable the OpenSSH daemon.
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
    settings.PermitRootLogin = "no";
  };

  # PostgreSQL for nextcloud + immich (shared instance). Pinned explicitly rather
  # than tracking the stateVersion default, so future stateVersion bumps don't
  # silently trigger another major upgrade. Moving 15 -> 17 is a deliberate
  # dump/restore migration (see docs/plan); the pg15 data dir is left intact.
  services.postgresql.package = pkgs.postgresql_17;

  # Enable NVIDIA
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.graphics.enable = true;
  # Driver >= 560 requires an explicit choice of kernel module flavour.
  # Closed modules are the safe default for unknown/pre-Turing GPUs.
  hardware.nvidia.open = false;

  # nix-ld so generic dynamically-linked binaries run (e.g. the official Claude
  # Code CLI in ~/.local/bin). Mirrors sulphur's modules/workstation.nix config.
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      zstd
      stdenv.cc.cc.lib
      zlib
      glib
      libGL
      libx11
      libxcursor
      libxrandr
      libxi
      libxkbcommon
      wayland
      fontconfig
      freetype
      dbus
    ];
  };

  # Enable Syncthing
  services.syncthing.enable = true;
  # GUI stays on localhost (default 127.0.0.1:8384) — reach it via SSH port-forward:
  #   ssh -L 8384:localhost:8384 sheath@10.0.0.10  ->  http://localhost:8384
  # Only open the sync protocol ports (22000/tcp+udp, 21027/udp discovery).
  services.syncthing.openDefaultPorts = true;

  # Disk layout, initrd modules, swap, hostPlatform and microcode all come from the
  # installer-generated ../hardware/hydrogen.nix (single source of disk-dependent config).
  hardware.enableRedistributableFirmware = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # bumped 23.11 -> 25.11 alongside the pg15->17 migration
}
