{ config, pkgs, lib, ... }: {
  imports = [
    ../hardware/hydrogen.nix          # generated by install.sh (disk UUIDs/mounts)
    ../modules/core.nix
    ../modules/sops.nix
    ../modules/impermanence-server.nix
    ../modules/reverse-proxy.nix
    ../modules/nextcloud.nix
    ../modules/immich.nix
    ../modules/calibre.nix
    ../modules/paperless.nix
    ../modules/scanner.nix
    ../modules/ollama.nix             # local LLM inference (loopback only), for paperless
    ../modules/backup.nix
    ../modules/auto-update.nix        # nightly stable-branch security updates (server runs 24/7)
    ../modules/fleet-vpn.nix          # on-demand WireGuard tunnel to the Jellyfin fleet (manual switch)
    ../modules/family/vpn-hub.nix     # wgadm (sulfur) + wgfam (family devices) -- see the firewall block below
    ../modules/minecraft-server.nix   # persistent vanilla world (system service, no session needed)
    ../modules/minecraft-couch.nix    # 1-4 player split-screen launcher on the projector
    ../modules/minecraft-client.nix   # the offline client (game + mods pinned), shared with sulfur
    # ../modules/veloren-server.nix   # DISABLED 2026-08-03 -- see below
    #
    # Veloren's rtsim (1867 NPCs across 196 sites) never idles: measured 20.7% of a core
    # continuously with ZERO players connected, versus 0.10% for the Minecraft server, which
    # does pause when empty (pause-when-empty-seconds, vanilla default 60). Nobody is playing
    # Veloren, so that is a permanent ~0.2 cores and ~700 MiB for nothing.
    #
    # To re-enable: uncomment the import above and the two ports in the br0 firewall lists
    # below. /var/lib/veloren is left in place, so characters and terrain diffs survive; even
    # if it were deleted the world regenerates identically from the pinned world_seed.
    # modules/veloren-server.nix and docs/veloren.md are unchanged.
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Adds a "Memory Test (memtest86+)" entry to the systemd-boot menu. Used to
  # diagnose the transient btrfs csum failures (RAM the prime suspect).
  boot.loader.systemd-boot.memtest86.enable = true;

  services.minecraftClient = {
    enable = true;

    # The couch pre-launcher passes --name and --server per player, so no defaults are
    # wanted here; and the entry point on this host is "Minecraft (Couch)" from
    # modules/minecraft-couch.nix, not a plain single-player launcher.
    desktopEntry = false;

    # THE RESTORE COPY. Everything the clients and the server need, mirrored into a
    # local binary cache on every switch that changes it, and picked up by the nightly
    # borg run (modules/backup.nix). This is what makes the setup survivable when
    # Mojang stops serving 1.21.10 or a mod disappears from Modrinth: the flake plus
    # this directory rebuild a playable client with no network at all.
    archiveDir = "/var/lib/minecraft-archive";
  };

  networking.hostName = "hydrogen"; # Define your hostname.

  # Enable networking. Plain `false` (not mkDefault) to override the mkDefault true
  # written into the generated hardware/hydrogen.nix; the static br0 bridge is used.
  networking.useDHCP = false;
  networking.wireless.enable = false;
  networking.bridges = {
    "br0" = {
      interfaces = ["enp0s31f6"];
    };
  };
  networking.interfaces.br0.ipv4.addresses = [{
    address = "10.0.0.10";
    prefixLength = 24;
  }];
  #networking.interfaces.enp0s31f6.ipv4.addresses = [{
    #address = "10.0.0.10";
    #prefixLength = 24;
  #}];
  networking.defaultGateway = "10.0.0.1";
  networking.nameservers = [ "10.0.0.1" ];
  networking.firewall.enable = true;

  # ---------------------------------------------------------------------------
  # THE ACCESS BOUNDARY. Read this whole block before changing any port anywhere.
  #
  # Every service on this box is reachable only over a WireGuard interface. Being on
  # the home wifi grants NOTHING -- not a service, not sshd. That is a deliberate change
  # from how this
  # host worked until now, and the reason is modules/minecraft-server.nix: that server
  # runs online-mode=false and verifies no identity, so whatever can reach 25565 may
  # claim to be any child. Scoping it to br0 meant "any device on the LAN", including
  # a guest phone and anything that ever gets onto the wifi.
  #
  # The two hubs are modules/family/vpn-hub.nix:
  #   wgadm (10.42.0.0/24, port 51822)  sulfur only -- full administrative access
  #   wgfam (10.41.0.0/24, port 51821)  family devices -- web + Minecraft, nothing else
  #
  # The router's own hub (vpn.luckyobserver.com:51820, 10.40.0.0/24) still exists and
  # still reaches the LAN, but it is NOT listed here and reaches no service -- as of
  # 2026-08-06 that includes sshd, so it is no longer a way into this host at all.
  #
  # Only the two WireGuard listen ports face the internet. The router forwards 51820,
  # 51821 and 51822/udp and nothing else -- verify that from off-tunnel after any router
  # change, as docs/minecraft.md has said all along.
  networking.firewall.allowedTCPPorts = [
    # Nothing. Every service port lives in an interface-scoped list below.
    #
    # Removed 2026-08-06: 6789, 7878, 8096, 8989 (sabnzbd/radarr/jellyfin/sonarr) --
    # modules/usenet.nix has not been imported by any host for a long time, so these
    # were open to the whole LAN for services that do not run.
  ];
  networking.firewall.allowedUDPPorts = [
    51821   # wgfam -- family devices
    51822   # wgadm -- sulfur
  ];

  # sshd's own firewall opener, OFF.
  #
  # services.openssh.openFirewall defaults to TRUE and adds 22 to the GLOBAL
  # allowedTCPPorts -- every interface, including br0. Removing the br0 entry below did
  # nothing for three days because of it: `nc -vz 10.0.0.10 22` from a LAN machine with
  # no key kept succeeding while every other port was correctly blocked, and the comment
  # here claimed the opposite.
  #
  # The lesson generalises past this option: an interface-scoped rule cannot subtract
  # from a global one. If a port must be reachable on exactly one interface, check that
  # nothing else is opening it globally first. 22 is in the wgadm list below, which is
  # now the only place it appears.
  services.openssh.openFirewall = false;

  # TEMPORARY -- REMOVE AFTER THE 2026-08-07 RENUMBER IS VERIFIED.
  #
  # The .1/.2/.3 rotation cannot be done without a break window: the router takes
  # 10.42.0.1 while this host still holds it, and two peers on one interface cannot
  # share an allowedIPs entry, so the addresses cannot coexist. With administration on
  # wgadm only, a mistake mid-rotation means the physical console.
  #
  # This is the net. Delete it, and this comment, once `ssh sheath@10.42.0.2` works.
  networking.firewall.interfaces."br0".allowedTCPPorts = [ 22 ];

  # br0 carries NOTHING. Not even SSH.
  #
  # 22 lived here until 2026-08-06 as break-glass -- a way back in when the tunnel
  # configuration itself was the broken thing. Removing it was a deliberate call: all
  # administration is on wgadm now, so there is no address on this LAN that answers.
  # (Removing it only actually took effect once openFirewall was disabled above.)
  #
  # WHAT THAT COSTS, so nobody has to rediscover it at a bad moment: if wgadm fails to
  # come up -- a bad switch, a rotated key, a sops decrypt that did not happen -- there
  # is no remote way in. Recovery is the physical console. That is survivable here
  # because this is a laptop with a working panel, GDM autologins sheath, and sheath has
  # NOPASSWD sudo, so a keyboard is a root shell. Do not remove any of those three
  # without restoring a network path first.
  environment.systemPackages = with pkgs; [
    rustdesk-flutter   # RustDesk host (this box is remote-controlled); LAN direct-IP
    rustup
    firefox
    git
    curl
    wget
    htop
    tree
    ripgrep
    srm
    # SMART tooling. /data is RAID0 over sda+sdb with no redundancy, and both
    # devices carry 4 btrfs corruption_errs, so drive health is worth being able
    # to read -- btrfs can detect corruption there but never repair it.
    smartmontools
    vlc
    p7zip
    neovim
    tmux
    rsync
    go

    # Veloren client (veloren-voxygen). Same derivation as the server in
    # modules/veloren-server.nix, which is the point: Veloren refuses cross-version
    # connections, so client and server must come from one flake pin. Airshipper is
    # not a substitute — it self-updates to upstream's weekly nightlies.
    veloren
  ];

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable libvirt
  virtualisation.libvirtd.enable = true;

  # Enable the GNOME Desktop Environment.
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  # NOTE: autoLogin for sheath is already enabled further below — that running
  # session (on the laptop's eDP panel) is what RustDesk captures for remote clients.

  # GNOME's power daemon initiates idle-suspend on its own (independent of the
  # masked systemd sleep targets below). hydrogen is a 24/7 server — never let
  # the session auto-suspend on idle. Also disable the lock screen + idle blanking
  # so remote-desktop capture (RustDesk) always has a live desktop on the eDP panel.
  # Applies to fresh sessions after rebuild.
  services.desktopManager.gnome.extraGSettingsOverrides = ''
    [org.gnome.settings-daemon.plugins.power]
    sleep-inactive-ac-type='nothing'
    sleep-inactive-battery-type='nothing'

    [org.gnome.desktop.screensaver]
    lock-enabled=false
    idle-activation-enabled=false

    [org.gnome.desktop.session]
    idle-delay=uint32 0
  '';
  services.desktopManager.gnome.extraGSettingsOverridePackages = [ pkgs.gnome-settings-daemon ];

  # RustDesk direct-IP remote desktop. Captures via the xdg-desktop-portal ScreenCast
  # path, which works on this NVIDIA+Wayland box — unlike gnome-remote-desktop RDP
  # (blank frames, mutter #3297) and Sunshine KMS capture (GL_INVALID_VALUE), both
  # tried and abandoned. Host app runs in the autologin session; set an unattended
  # password + enable direct-IP in its Security settings. 21118 is the direct-access
  # port; open its full range.
  #
  # Direct-IP now means the wgadm address 10.42.0.1, not 10.0.0.10 — it moved off the
  # LAN with everything else. Update the saved connection on sulfur accordingly.

  # --- wgadm: sulfur, full administrative access ------------------------------
  networking.firewall.interfaces."wgadm".allowedTCPPorts = [
    22                              # SSH (also on br0 as break-glass, above)
    80 443                          # the vhosts in modules/reverse-proxy.nix
    25565                           # Minecraft (modules/minecraft-server.nix)
    21115 21116 21117 21118 21119   # RustDesk (see the comment above this block)
    22000                           # Syncthing sync protocol
  ];
  networking.firewall.interfaces."wgadm".allowedUDPPorts = [
    21116           # RustDesk
    22000 21027     # Syncthing sync + local discovery
  ];

  # --- wgfam: family devices --------------------------------------------------
  # Web services and the game. Note what is absent: 22, RustDesk, Syncthing. A family
  # peer that tries them is rejected here even before hydrogen's FORWARD policy
  # (modules/family/vpn-hub.nix) stops it addressing anything but this host.
  networking.firewall.interfaces."wgfam".allowedTCPPorts = [
    80 443
    25565

    # Veloren game port (modules/veloren-server.nix). Closed alongside the disabled
    # import above; re-open with it, here rather than on br0 -- that server also runs
    # with auth_server_address: None and verifies no identity, so it belongs behind the
    # tunnel for exactly the reason 25565 does.
    # 14004
  ];
  # networking.firewall.interfaces."wgfam".allowedUDPPorts = [ 14006 ]; # Veloren query

  # Auto-start the RustDesk host with the (autologin) graphical session, so the box
  # accepts connections after boot without launching it by hand. Runs as a user
  # service under graphical-session.target so it inherits the Wayland/DBus/portal
  # env needed for screen capture. Unattended password + direct-IP are set once in
  # the app (stateful, in ~/.config/rustdesk).
  systemd.user.services.rustdesk = {
    description = "RustDesk remote-desktop host";
    partOf = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    wantedBy = [ "graphical-session.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.rustdesk-flutter}/bin/rustdesk";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enable automatic login for the primary user.
  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "sheath";

  # Workaround for GNOME autologin: https://github.com/NixOS/nixpkgs/issues/103746#issuecomment-945091229
  systemd.services."getty@tty1".enable = false;
  systemd.services."autovt@tty1".enable = false;

  # Disable suspend. The masks are the last line of defence and stay: an
  # unnoticed suspend would take Minecraft, Nextcloud, Immich, Paperless and the
  # nightly backups offline at once, which is far worse than a failed attempt.
  systemd.targets.sleep.enable = false;
  systemd.targets.suspend.enable = false;
  systemd.targets.hibernate.enable = false;
  systemd.targets.hybrid-sleep.enable = false;

  # ...but logind must never TRY, because a masked target is not a graceful "no".
  #
  # 2026-08-04: systemd-logind wedged in a tight retry loop -- "Suspending..." ->
  # "Unit suspend.target is masked, refusing operation." -> "Permission denied",
  # roughly 240 times a second, burning 75% of a core. A bus capture showed ZERO
  # messages addressed to login1: nothing asked it to suspend, it was re-querying
  # suspend.target's LoadState from PID 1 on its own and never clearing the
  # pending operation. It produced ~7M journal lines in four hours, which blew
  # past journald's retention and evicted the rest of the day -- including the
  # 03:00 backup window, so the nightly borg run had no diagnosable record.
  #
  # The masks are what turn a refusal into a livelock, so the fix is to make
  # logind never initiate a sleep operation in the first place. SleepOperation=
  # (empty) leaves it no candidate operation at all; the Handle*Key entries stop
  # a stray ACPI/keyboard event from starting one. IdleAction and the lid
  # switches were already covered.
  #
  # If this ever recurs, it is one command to confirm:
  #   journalctl -u systemd-logind | grep -c "refusing operation"
  # and `systemctl restart systemd-logind` clears the wedged state.
  services.logind.settings.Login = {
    IdleAction = "ignore";
    HandleLidSwitch = "ignore";
    HandleLidSwitchDocked = "ignore";
    HandleLidSwitchExternalPower = "ignore";
    HandleSuspendKey = "ignore";
    HandleSuspendKeyLongPress = "ignore";
    HandleHibernateKey = "ignore";
    HandleHibernateKeyLongPress = "ignore";
    SleepOperation = "";
  };

  # Xeon E-2176M with HWP. The default balanced energy-performance preference
  # leaves frames on the table under sustained load (four Minecraft clients plus
  # the server), and this box is mains-powered 24/7.
  powerManagement.cpuFreqGovernor = "performance";

  # (allowUnfree is set centrally in flake.nix commonModules)

  # Enable the OpenSSH daemon.
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
    settings.PermitRootLogin = "no";
  };

  # ---------------------------------------------------------------------------
  # Declarative passwords, from sops.
  #
  # mutableUsers = false is what makes the declared hashes authoritative; with the
  # default (true) NixOS only applies a declared password when it CREATES the account,
  # so setting hashedPasswordFile alone would change nothing on this running system.
  #
  # THE CONSEQUENCE, stated plainly: this also discards the root password that was set
  # interactively at install time. Declared state becomes the whole state. That is why
  # root is declared here as well -- without it the systemd emergency shell would have no
  # way in, and a server that cannot be rescued from its own console is a bad trade for a
  # tidier password story. (nixpkgs' assertion in config/users-groups.nix would still pass
  # on sheath's key alone; passing that assertion is not the same as being recoverable.)
  #
  # Ordering works because modules/impermanence-server.nix marks /persist neededForBoot,
  # so the age key at /persist/secrets/age-keys.txt is readable before
  # sops-install-secrets-for-users runs. Read that comment before changing either.
  #
  # sheath's hash comes from secrets/family.yaml -- encrypted to the main key AND the
  # family key, so hydrogen, sulfur and the four laptops all share one entry. root's stays
  # in secrets/secrets.yaml: the kids' laptops have no business with it and leave root
  # locked on purpose.
  users.mutableUsers = false;

  sops.secrets."sheath-password-hash" = {
    sopsFile = ../secrets/family.yaml;
    neededForUsers = true;
  };
  sops.secrets."root-password-hash".neededForUsers = true;

  users.users.sheath.hashedPasswordFile = config.sops.secrets."sheath-password-hash".path;
  users.users.root.hashedPasswordFile = config.sops.secrets."root-password-hash".path;

  # PostgreSQL for nextcloud + immich (shared instance). Pinned explicitly rather
  # than tracking the stateVersion default, so future stateVersion bumps don't
  # silently trigger another major upgrade. Moving 15 -> 17 is a deliberate
  # dump/restore migration (see docs/plan); the pg15 data dir is left intact.
  services.postgresql.package = pkgs.postgresql_17;

  # Enable NVIDIA
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.graphics.enable = true;
  # Cheap insurance against a Steam/Proton-shaped "missing 32-bit lib" rabbit
  # hole later; costs a few hundred MB of closure.
  hardware.graphics.enable32Bit = true;
  # Driver >= 560 requires an explicit choice of kernel module flavour.
  # Closed modules are the safe default for unknown/pre-Turing GPUs.
  hardware.nvidia.open = false;

  # The Quadro P4200 is Pascal (GP104GLM), and Pascal is end-of-life: R580 is the
  # last branch NVIDIA supports for Maxwell/Pascal/Volta, with critical security
  # updates for Quadro parts through October 2028 but no further feature updates.
  # Every branch in the current nixpkgs pin (stable/latest/beta/production) is
  # 580.142, so this pin is a no-op TODAY — its job is to stop the nightly
  # auto-update (modules/auto-update.nix) from silently moving the GPU onto a 590
  # branch that does not support this card. Revisit deliberately at the next
  # NixOS release bump; when nixpkgs grows a legacy_580 attribute, switch to it.
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.production;

  # nix-ld so generic dynamically-linked binaries run (e.g. the official Claude
  # Code CLI in ~/.local/bin). Mirrors sulfur's modules/workstation.nix config.
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      zstd
      stdenv.cc.cc.lib
      zlib
      glib
      libGL
      libx11
      libxcursor
      libxrandr
      libxi
      libxkbcommon
      wayland
      fontconfig
      freetype
      dbus
    ];
  };

  # Enable Syncthing
  services.syncthing.enable = true;
  # GUI stays on localhost (default 127.0.0.1:8384) — reach it via SSH port-forward:
  #   ssh -L 8384:localhost:8384 sheath@10.42.0.1  ->  http://localhost:8384
  #
  # openDefaultPorts opens 22000/tcp+udp and 21027/udp on EVERY interface, which is the
  # one thing this host no longer does. The same ports are listed under wgadm above, so
  # sulfur syncs over the admin tunnel and nothing else can reach the daemon.
  #
  # sulfur is the only peer that syncs with this host, and it is on wgadm, so nothing is
  # lost. Should another machine ever need to sync, give it a wgadm peer rather than
  # re-opening these ports on br0.
  services.syncthing.openDefaultPorts = false;

  # Disk layout, initrd modules, swap, hostPlatform and microcode all come from the
  # installer-generated ../hardware/hydrogen.nix (single source of disk-dependent config).
  hardware.enableRedistributableFirmware = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # bumped 23.11 -> 25.11 alongside the pg15->17 migration
}
