{ pkgs }:
# Every byte the Minecraft client needs to run, pinned by hash and laid out exactly the
# way portablemc expects to find an installation ("main dir", the thing normally called
# .minecraft/).
#
# WHY THIS EXISTS. Prism -- and any other launcher -- keeps this payload as undeclared
# state and refetches it from Mojang whenever it is missing. That makes a restore
# depend on Mojang still serving 1.21.10 and on a cached Microsoft account. Pinning it
# means the client can be rebuilt from the flake alone, and its closure can be archived
# to hydrogen (modules/minecraft-client.nix) and restored from there with no network at
# all.
#
# HOW PORTABLEMC IS MADE TO NEVER DOWNLOAD. It skips any file already present at the
# expected size, so with the whole payload pre-placed its download list comes out empty.
# The launcher additionally passes --fetch-exclude-all, which drops the version-manifest
# re-validation that would otherwise still go out. Two consequences shape the layout
# below:
#
#   - the main dir is only ever READ, so it can be this store path directly. Everything
#     portablemc writes -- the extracted natives, any cached metadata -- is directed at
#     the game directory by the launcher's --mc-dir/--bin-dir, which is per-player state.
#     NOTE that --bin-dir defaults off --main-dir, not --mc-dir, despite what its help
#     text says; without it, natives extraction hits this store path. See the launcher.
#   - a missing or wrong-sized file does not silently redownload into a read-only store
#     path, it fails the launch. That is the failure mode we want: a payload gap is a
#     packaging bug, not something to paper over at runtime.
#
# TO UPDATE: ./update.sh <mc-version>, then rebuild and paste the assets hash it
# reports back into assetObjects below. The Fabric side comes from
# packages/fabric-server.nix, so the loader is bumped there, once, for both sides.
let
  inherit (pkgs) lib;

  # Generated by ./update.sh; a repo file, so reading it is not import-from-derivation.
  lock = builtins.fromJSON (builtins.readFile ./libraries.json);
  inherit (lock) mcVersion assetIndexId;

  fabric = import ../fabric-server.nix { inherit pkgs; };
  inherit (fabric) loaderVersion loaderLibs;

  # Fabric's own naming, and therefore the id portablemc is given on the command line.
  versionId = "fabric-loader-${loaderVersion}-${mcVersion}";

  versionJson = pkgs.fetchurl {
    name = "minecraft-${mcVersion}.json";
    inherit (lock.versionJson) url hash;
  };

  clientJar = pkgs.fetchurl {
    name = "minecraft-client-${mcVersion}.jar";
    inherit (lock.clientJar) url hash;
  };

  assetIndex = pkgs.fetchurl {
    name = "minecraft-assets-${assetIndexId}.json";
    inherit (lock.assetIndex) url hash;
  };

  # The log4j2 configuration the game is started with. A kilobyte of XML, and the only
  # payload file that is neither a library, an asset nor metadata -- easy to overlook,
  # and portablemc will happily try to download it mid-launch if it is missing.
  logConfig = pkgs.fetchurl {
    name = "minecraft-${lock.logConfig.id}";
    inherit (lock.logConfig) url hash;
  };

  # ---------------------------------------------------------------------------
  # The ~4.6k asset objects (sounds, languages, panorama, icons): 424 MiB.
  #
  # ONE fixed-output derivation rather than a fetchurl per object. The objects are
  # content-addressed upstream -- the URL ends in the file's own sha1 -- so the tree is
  # bit-identical on every fetch and a single recursive output hash pins the lot. Four
  # thousand individual fetchurls would pin it just as well but would mean four thousand
  # store paths and an eval to match.
  #
  # ASSETS HASH: when the asset index changes (a new Minecraft version, essentially),
  # this hash changes with it. Build once with the old hash, and Nix prints the correct
  # one in the mismatch error.
  # ---------------------------------------------------------------------------
  assetObjects = pkgs.stdenv.mkDerivation {
    pname = "minecraft-assets";
    version = assetIndexId;

    dontUnpack = true;
    # Nothing here is an executable; the default fixup phase has nothing to do and only
    # gets a chance to perturb the tree the output hash is taken over.
    dontFixup = true;
    nativeBuildInputs = with pkgs; [ curl jq ];

    # A fixed-output derivation gets network access but not the host's environment, so
    # the CA bundle has to be named explicitly -- pkgs.fetchurl does the same thing
    # behind the scenes. The proxy variables are the standard fetcher passthrough.
    SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
    impureEnvVars = lib.fetchers.proxyImpureEnvVars;

    buildPhase = ''
      runHook preBuild

      mkdir -p objects

      # One curl process for the whole set: --parallel multiplexes over a handful of
      # connections, which is the difference between two minutes and twenty. The config
      # file form is the only way to give it 4.6k url/output pairs.
      jq -r '.objects | to_entries | map(.value.hash) | unique | .[]
             | "url = \"https://resources.download.minecraft.net/\(.[0:2])/\(.)\"",
               "output = \"objects/\(.[0:2])/\(.)\""' ${assetIndex} > curlrc

      # curl will not create the two-character prefix directories itself.
      jq -r '.objects | to_entries | map(.value.hash[0:2]) | unique | .[]' ${assetIndex} \
        | sed 's|^|objects/|' | xargs mkdir -p

      curl --parallel --parallel-max 16 \
           --retry 5 --retry-delay 2 --retry-connrefused \
           --fail --silent --show-error --location \
           --config curlrc

      # Belt and braces: the output hash below would catch a corrupt download, but only
      # as an opaque mismatch. Checking each object against the sha1 the index states
      # points straight at the bad file instead.
      jq -r '.objects | to_entries | map(.value.hash) | unique | .[]
             | "\(.)  objects/\(.[0:2])/\(.)"' ${assetIndex} > SHA1SUMS
      sha1sum --quiet --check SHA1SUMS

      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall
      mkdir -p $out
      cp -r objects $out/objects
      # Deterministic permissions: the NAR the output hash is taken over records the
      # executable bit, and nothing here should have it.
      chmod -R a-w,a+rX $out
      runHook postInstall
    '';

    outputHashMode = "recursive";
    outputHashAlgo = "sha256";
    outputHash = "sha256-sEAQZbWfL8ChGOc+opvlShDgmyxpZBHzMMDcBxYr1mk=";
  };

  # ---------------------------------------------------------------------------
  # The Fabric launch profile, GENERATED rather than fetched.
  #
  # meta.fabricmc.net's /profile/json endpoint stamps `releaseTime` and `time` with the
  # moment of the request, so the same URL returns different bytes every time and there
  # is no hash to pin. Writing it here also means the library list is the one
  # packages/fabric-server.nix already pins, instead of a second copy that can drift.
  #
  # Transcribed from
  #   https://meta.fabricmc.net/v2/versions/loader/1.21.10/0.19.3/profile/json
  # The only difference from the server profile is the main class -- KnotClient rather
  # than KnotServer -- and the -DFabricMcEmu argument, which tells Fabric which class
  # the game "really" started from so crash reports and mods that inspect the stack see
  # net.minecraft.client.main.Main. Its leading and trailing spaces are upstream's and
  # are load-bearing; it is one argv element, not three.
  #
  # `inheritsFrom` is what makes portablemc load the vanilla metadata underneath this
  # one and merge the two -- verified in 5.0.3, which reports loading both
  # fabric-loader-0.19.3-1.21.10 and the 1.21.10 beneath it. The libraries use the
  # {name, url} repo-root form, which resolves to <url><maven path> -- and since every
  # one of those paths is populated below, nothing is ever fetched from it.
  # ---------------------------------------------------------------------------
  fabricProfile = pkgs.writeText "${versionId}.json" (builtins.toJSON {
    id = versionId;
    inheritsFrom = mcVersion;
    type = "release";
    mainClass = "net.fabricmc.loader.impl.launch.knot.KnotClient";
    arguments = {
      game = [ ];
      jvm = [ "-DFabricMcEmu= net.minecraft.client.main.Main " ];
    };
    libraries = map (l: {
      name = l.spec;
      url = "https://maven.fabricmc.net/";
    }) loaderLibs;
  });

  # Vanilla's 115 libraries plus Fabric's 8, each at its maven path. portablemc derives
  # that path from the coordinate (portablemc/util.py:120-134), so it has to match
  # exactly -- note sponge-mixin's literal '+', which the download URL percent-encodes.
  libraryLinks =
    map (l: { name = "libraries/${l.path}"; path = pkgs.fetchurl { inherit (l) url hash; }; }) lock.libraries
    ++ map (l: { name = "libraries/${l.path}"; path = l.jar; }) loaderLibs;
in
(pkgs.linkFarm "minecraft-client-${mcVersion}" (libraryLinks ++ [
  # The vanilla metadata, byte-for-byte as Mojang serves it. portablemc re-checks this
  # file's sha1 against the version manifest whenever it can reach the network and
  # refetches it if they differ, so a reformatted copy would be redownloaded -- into a
  # read-only store path. The launcher's --fetch-exclude-all now suppresses that check,
  # but keep the bytes exact anyway: it is one flag away from mattering again.
  { name = "versions/${mcVersion}/${mcVersion}.json"; path = versionJson; }

  { name = "versions/${versionId}/${versionId}.json"; path = fabricProfile; }

  # Not a mistake: the game jar is looked up under the RESOLVED version's directory
  # which is the Fabric one,
  # while the download entry describing it comes from the vanilla metadata underneath.
  # Fabric adds no jar of its own -- it launches the vanilla one through its loader.
  { name = "versions/${versionId}/${versionId}.jar"; path = clientJar; }

  { name = "assets/indexes/${assetIndexId}.json"; path = assetIndex; }
  { name = "assets/objects"; path = "${assetObjects}/objects"; }
  { name = "assets/log_configs/${lock.logConfig.id}"; path = logConfig; }
])).overrideAttrs
  (old: {
    passthru = (old.passthru or { }) // {
      inherit mcVersion loaderVersion versionId assetIndexId;
      # The major Java version Mojang states for this release; the launcher pins the
      # JDK to it rather than taking whatever is on PATH.
      javaVersion = lock.javaVersion;
      inherit assetObjects;
    };

    meta = {
      description = "Offline Minecraft ${mcVersion} client payload with Fabric Loader ${loaderVersion}";
      # Inherited from the game jar and assets this assembles.
      license = lib.licenses.unfreeRedistributable;
      platforms = lib.platforms.linux;
    };
  })
